#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App1.Resource", IsApplication=true)]

namespace App1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int circle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int conversation = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int img = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int options_menu = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int user = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int user1 = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int Cnumber = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int ContactImage = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int ContactName = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int ContactsListView = 2131034120;
			
			// aapt resource value: 0x7f050032
			public const int Profile = 2131034162;
			
			// aapt resource value: 0x7f050024
			public const int ReceiverTxt = 2131034148;
			
			// aapt resource value: 0x7f050031
			public const int SenderTxt = 2131034161;
			
			// aapt resource value: 0x7f05001b
			public const int btnChangePropic = 2131034139;
			
			// aapt resource value: 0x7f050016
			public const int btnLoginLL = 2131034134;
			
			// aapt resource value: 0x7f050030
			public const int btnRegister = 2131034160;
			
			// aapt resource value: 0x7f05000f
			public const int btnSend = 2131034127;
			
			// aapt resource value: 0x7f050020
			public const int btnUpload = 2131034144;
			
			// aapt resource value: 0x7f050019
			public const int btnVerify = 2131034137;
			
			// aapt resource value: 0x7f05001f
			public const int btnuploadpropic = 2131034143;
			
			// aapt resource value: 0x7f050004
			public const int chatList = 2131034116;
			
			// aapt resource value: 0x7f050010
			public const int imageView1 = 2131034128;
			
			// aapt resource value: 0x7f050001
			public const int imgBtnProfile = 2131034113;
			
			// aapt resource value: 0x7f05001e
			public const int imgbtnGallery = 2131034142;
			
			// aapt resource value: 0x7f050011
			public const int lblPassword = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int linearLayoutBtns = 2131034132;
			
			// aapt resource value: 0x7f050034
			public const int newChat = 2131034164;
			
			// aapt resource value: 0x7f05001a
			public const int propicview = 2131034138;
			
			// aapt resource value: 0x7f050009
			public const int receiverList = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int relativeLayout1 = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int relativeLayout2 = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int senderList = 2131034122;
			
			// aapt resource value: 0x7f050033
			public const int settings = 2131034163;
			
			// aapt resource value: 0x7f050021
			public const int tableLayout1 = 2131034145;
			
			// aapt resource value: 0x7f05000c
			public const int tableLayout2 = 2131034124;
			
			// aapt resource value: 0x7f050022
			public const int tableRow1 = 2131034146;
			
			// aapt resource value: 0x7f05000d
			public const int tableRow3 = 2131034125;
			
			// aapt resource value: 0x7f050025
			public const int tableRow4 = 2131034149;
			
			// aapt resource value: 0x7f050017
			public const int textView1 = 2131034135;
			
			// aapt resource value: 0x7f050023
			public const int textView12 = 2131034147;
			
			// aapt resource value: 0x7f050026
			public const int textView14 = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int textView15 = 2131034151;
			
			// aapt resource value: 0x7f050029
			public const int textView16 = 2131034153;
			
			// aapt resource value: 0x7f05002c
			public const int textView17 = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int txtAddress = 2131034157;
			
			// aapt resource value: 0x7f050002
			public const int txtContactName = 2131034114;
			
			// aapt resource value: 0x7f05002b
			public const int txtEmail = 2131034155;
			
			// aapt resource value: 0x7f050028
			public const int txtFullName = 2131034152;
			
			// aapt resource value: 0x7f050003
			public const int txtLastMessage = 2131034115;
			
			// aapt resource value: 0x7f05002a
			public const int txtMobileNumber = 2131034154;
			
			// aapt resource value: 0x7f05001d
			public const int txtNumber = 2131034141;
			
			// aapt resource value: 0x7f050018
			public const int txtOtp = 2131034136;
			
			// aapt resource value: 0x7f05002e
			public const int txtPass = 2131034158;
			
			// aapt resource value: 0x7f050015
			public const int txtPassword = 2131034133;
			
			// aapt resource value: 0x7f050013
			public const int txtPhoneNumber = 2131034131;
			
			// aapt resource value: 0x7f05002f
			public const int txtRePass = 2131034159;
			
			// aapt resource value: 0x7f050012
			public const int txtUsername = 2131034130;
			
			// aapt resource value: 0x7f05000e
			public const int txtmsg = 2131034126;
			
			// aapt resource value: 0x7f05001c
			public const int txtusername = 2131034140;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChatListCell = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChatListLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ContactListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ContactPickLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ConversationLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int login = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int OtpReceiverLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ProfileImageLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ProfilePickLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ProfilePictureSetLayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ReceiverCell = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Registration = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SenderCell = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int StartLayout = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
